higher_lower_dataset = [
    {'name': 'Cristiano Ronaldo', 'username': 'cristiano', 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Ariana Grande', 'username': 'arianagrande', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Dwayne Johnson', 'username': 'therock', 'description': 'Actor and former wrestler', 'country': 'USA'},
    {'name': 'Kim Kardashian', 'username': 'kimkardashian', 'description': 'TV personality', 'country': 'USA'},
    {'name': 'Selena Gomez', 'username': 'selenagomez', 'description': 'Singer and actress', 'country': 'USA'},
    {'name': 'Lionel Messi', 'username': 'leomessi', 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Kylie Jenner', 'username': 'kyliejenner', 'description': 'Businesswoman', 'country': 'USA'},
    {'name': 'Beyoncé', 'username': 'beyonce', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Justin Bieber', 'username': 'justinbieber', 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Taylor Swift', 'username': 'taylorswift', 'description': 'Singer-songwriter', 'country': 'USA'},
    {'name': 'Neymar Jr', 'username': 'neymarjr', 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Virat Kohli', 'username': 'virat.kohli', 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Shakira', 'username': 'shakira', 'description': 'Singer', 'country': 'Colombia'},
    {'name': 'Jennifer Lopez', 'username': 'jlo', 'description': 'Singer and actress', 'country': 'USA'},
    {'name': 'Will Smith', 'username': 'willsmith', 'description': 'Actor and musician', 'country': 'USA'},
    {'name': 'LeBron James', 'username': 'kingjames', 'description': 'Basketball player', 'country': 'USA'},
    {'name': 'Priyanka Chopra', 'username': 'priyankachopra', 'description': 'Actress and producer', 'country': 'India'},
    {'name': 'Billie Eilish', 'username': 'billieeilish', 'description': 'Singer-songwriter', 'country': 'USA'},
    {'name': 'Miley Cyrus', 'username': 'mileycyrus', 'description': 'Singer and actress', 'country': 'USA'},
    {'name': 'Zendaya', 'username': 'zendaya', 'description': 'Actress and singer', 'country': 'USA'},
    {'name': 'Khloe Kardashian', 'username': 'khloekardashian', 'description': 'TV personality', 'country': 'USA'},
    {'name': 'Shawn Mendes', 'username': 'shawnmendes', 'description': 'Singer-songwriter', 'country': 'Canada'},
    {'name': 'Gigi Hadid', 'username': 'gigihadid', 'description': 'Model', 'country': 'USA'},
    {'name': 'Kevin Hart', 'username': 'kevinhart4real', 'description': 'Comedian and actor', 'country': 'USA'},
    {'name': 'Zlatan Ibrahimović', 'username': 'iamzlatanibrahimovic', 'description': 'Footballer', 'country': 'Sweden'},
    {'name': 'Katy Perry', 'username': 'katyperry', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Drake', 'username': 'champagnepapi', 'description': 'Rapper', 'country': 'Canada'},
    {'name': 'Nicki Minaj', 'username': 'nickiminaj', 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Chris Hemsworth', 'username': 'chrishemsworth', 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Rihanna', 'username': 'badgalriri', 'description': 'Singer and entrepreneur', 'country': 'Barbados'},
    {'name': 'David Beckham', 'username': 'davidbeckham', 'description': 'Footballer', 'country': 'UK'},
    {'name': 'Jason Derulo', 'username': 'jasonderulo', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Chris Evans', 'username': 'chrisevans', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Kourtney Kardashian', 'username': 'kourtneykardash', 'description': 'TV personality', 'country': 'USA'},
    {'name': 'Hugh Jackman', 'username': 'thehughjackman', 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Demi Lovato', 'username': 'ddlovato', 'description': 'Singer and actress', 'country': 'USA'},
    {'name': 'Tom Holland', 'username': 'tomholland2013', 'description': 'Actor', 'country': 'UK'},
    {'name': 'Camila Cabello', 'username': 'camila_cabello', 'description': 'Singer-songwriter', 'country': 'USA'},
    {'name': 'Mark Zuckerberg', 'username': 'zuck', 'description': 'CEO of Meta', 'country': 'USA'},
    {'name': 'PewDiePie', 'username': 'pewdiepie', 'description': 'YouTuber', 'country': 'Sweden'},
    {'name': 'Ed Sheeran', 'username': 'teddysphotos', 'description': 'Singer-songwriter', 'country': 'UK'},
    {'name': 'Luis Suarez', 'username': 'luissuarez9', 'description': 'Footballer', 'country': 'Uruguay'},
    {'name': 'Cardi B', 'username': 'iamcardib', 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Post Malone', 'username': 'postmalone', 'description': 'Rapper and singer', 'country': 'USA'},
    {'name': 'Snoop Dogg', 'username': 'snoopdogg', 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Maluma', 'username': 'maluma', 'description': 'Singer', 'country': 'Colombia'},
    {'name': 'Deepika Padukone', 'username': 'deepikapadukone', 'description': 'Actress', 'country': 'India'},
    {'name': 'Virgil van Dijk', 'username': 'virgilvandijk', 'description': 'Footballer', 'country': 'Netherlands'},
    {'name': 'Shah Rukh Khan', 'username': 'iamsrk', 'description': 'Actor', 'country': 'India'},
    {'name': 'Sachin Tendulkar', 'username': 'sachintendulkar', 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Chris Pratt', 'username': 'prattprattpratt', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Gal Gadot', 'username': 'gal_gadot', 'description': 'Actress', 'country': 'Israel'},
    {'name': 'Zayn Malik', 'username': 'zayn', 'description': 'Singer', 'country': 'UK'},
    {'name': 'Kanye West', 'username': 'ye', 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Vin Diesel', 'username': 'vindiesel', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Emma Watson', 'username': 'emmawatson', 'description': 'Actress', 'country': 'UK'},
    {'name': 'Jason Momoa', 'username': 'prideofgypsies', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Paris Hilton', 'username': 'parishilton', 'description': 'Media personality', 'country': 'USA'},
    {'name': 'Bruno Mars', 'username': 'brunomars', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Adele', 'username': 'adele', 'description': 'Singer', 'country': 'UK'},
    {'name': 'Millie Bobby Brown', 'username': 'milliebobbybrown', 'description': 'Actress', 'country': 'UK'},
    {'name': 'Chris Brown', 'username': 'chrisbrownofficial', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Eva Mendes', 'username': 'evamendes', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Bella Hadid', 'username': 'bellahadid', 'description': 'Model', 'country': 'USA'},
    {'name': 'Hrithik Roshan', 'username': 'hrithikroshan', 'description': 'Actor', 'country': 'India'},
    {'name': 'Gwen Stefani', 'username': 'gwenstefani', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Cameron Diaz', 'username': 'camerondiaz', 'description': 'Actress', 'country': 'USA'},
    {'name': 'John Legend', 'username': 'johnlegend', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Camila Mendes', 'username': 'camimendes', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Ellen DeGeneres', 'username': 'ellendegeneres', 'description': 'TV host', 'country': 'USA'},
    {'name': 'Rita Ora', 'username': 'ritaora', 'description': 'Singer', 'country': 'UK'},
    {'name': 'Niall Horan', 'username': 'niallhoran', 'description': 'Singer', 'country': 'Ireland'},
    {'name': 'Travis Scott', 'username': 'travisscott', 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Charlie Puth', 'username': 'charlieputh', 'description': 'Singer-songwriter', 'country': 'USA'},
    {'name': 'Diljit Dosanjh', 'username': 'diljitdosanjh', 'description': 'Singer and actor', 'country': 'India'},
    {'name': 'Billie Lourd', 'username': 'praisethelourd', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Chadwick Boseman', 'username': 'chadwickboseman', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Nicole Scherzinger', 'username': 'nicolescherzinger', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Alicia Keys', 'username': 'aliciakeys', 'description': 'Singer-songwriter', 'country': 'USA'},
    {'name': 'Karan Aujla', 'username': 'karanaujla', 'description': 'Singer and rapper', 'country': 'India'},
    {'name': 'Lucy Hale', 'username': 'lucyhale', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Miranda Lambert', 'username': 'mirandalambert', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Katherine Langford', 'username': 'katherinelangford', 'description': 'Actress', 'country': 'Australia'},
    {'name': 'Keke Palmer', 'username': 'keke', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Danielle Peazer', 'username': 'daniellepeazer', 'description': 'Dancer', 'country': 'UK'},
    {'name': 'Steve Aoki', 'username': 'steveaoki', 'description': 'DJ', 'country': 'USA'},
    {'name': 'Nina Dobrev', 'username': 'nina', 'description': 'Actress', 'country': 'Canada'},
    {'name': 'Sophie Turner', 'username': 'sophiet', 'description': 'Actress', 'country': 'UK'},
    {'name': 'Camilla Belle', 'username': 'camillabelle', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Sabrina Carpenter', 'username': 'sabrinacarpenter', 'description': 'Singer and actress', 'country': 'USA'},
    {'name': 'Patrick Mahomes', 'username': 'patrickmahomes', 'description': 'American football player', 'country': 'USA'},
    {'name': 'Gina Rodriguez', 'username': 'hereisgina', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Katherine McNamara', 'username': 'kat.mcnamara', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Janelle Monáe', 'username': 'janellemonae', 'description': 'Singer and actress', 'country': 'USA'},
    {'name': 'Marilyn Manson', 'username': 'marilynmanson', 'description': 'Musician', 'country': 'USA'},
    {'name': 'Bella Thorne', 'username': 'bellathorne', 'description': 'Actress and singer', 'country': 'USA'},
    {'name': 'Ashanti', 'username': 'ashanti', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Ne-Yo', 'username': 'neyo', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Kacey Musgraves', 'username': 'spaceykacey', 'description': 'Singer-songwriter', 'country': 'USA'},
    {'name': 'Lil Nas X', 'username': 'lilnasx', 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Megan Fox', 'username': 'meganfox', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Halsey', 'username': 'iamhalsey', 'description': 'Singer-songwriter', 'country': 'USA'},
    {'name': 'Lizzo', 'username': 'lizzobeeating', 'description': 'Singer and rapper', 'country': 'USA'},
    {'name': 'Wiz Khalifa', 'username': 'wizkhalifa', 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Tinashe', 'username': 'tinashenow', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Brie Larson', 'username': 'brielarson', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Julianne Hough', 'username': 'juleshough', 'description': 'Dancer and actress', 'country': 'USA'},
    {'name': 'Alessia Cara', 'username': 'alessiasmusic', 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Misty Copeland', 'username': 'mistyonpointe', 'description': 'Ballet dancer', 'country': 'USA'},
    {'name': 'Nelly', 'username': 'nelly', 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Kerry Washington', 'username': 'kerrywashington', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Angela Bassett', 'username': 'im.angelabassett', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Tyra Banks', 'username': 'tyrabanks', 'description': 'Model and TV personality', 'country': 'USA'},
    {'name': 'Jessica Alba', 'username': 'jessicaalba', 'description': 'Actress and entrepreneur', 'country': 'USA'},
    {'name': 'Kylie Minogue', 'username': 'kylieminogue', 'description': 'Singer', 'country': 'Australia'},
    {'name': 'Jack Black', 'username': 'jackblack', 'description': 'Actor and musician', 'country': 'USA'},
    {'name': 'Naomi Campbell', 'username': 'naomi', 'description': 'Model', 'country': 'UK'},
    {'name': 'Ashley Tisdale', 'username': 'ashleytisdale', 'description': 'Actress and singer', 'country': 'USA'},
    {'name': 'Vanessa Hudgens', 'username': 'vanessahudgens', 'description': 'Actress and singer', 'country': 'USA'},
    {'name': 'Jesse McCartney', 'username': 'jessemccartney', 'description': 'Singer and actor', 'country': 'USA'},
    {'name': 'Bella Poarch', 'username': 'bellapoarch', 'description': 'Social media personality', 'country': 'USA'},
    {'name': 'Lindsay Lohan', 'username': 'lindsaylohan', 'description': 'Actress and singer', 'country': 'USA'},
    {'name': 'Tyler Posey', 'username': 'tylerposey58', 'description': 'Actor', 'country': 'USA'},
    {'name': 'John Cena', 'username': 'johncena', 'description': 'Wrestler and actor', 'country': 'USA'},
    {'name': 'Sydney Sweeney', 'username': 'sydney_sweeney', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Jennifer Aniston', 'username': 'jenniferaniston', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Diane Kruger', 'username': 'dianekruger', 'description': 'Actress', 'country': 'Germany'},
    {'name': 'Natalie Portman', 'username': 'natalieportman', 'description': 'Actress', 'country': 'Israel'},
    {'name': 'Olivia Rodrigo', 'username': 'oliviarodrigo', 'description': 'Singer-songwriter', 'country': 'USA'},
    {'name': 'Jessica Chastain', 'username': 'jessicachastain', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Chloe Grace Moretz', 'username': 'chloegmoretz', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Lily Collins', 'username': 'lilyjcollins', 'description': 'Actress', 'country': 'UK'},
    {'name': 'Hailee Steinfeld', 'username': 'haileesteinfeld', 'description': 'Actress and singer', 'country': 'USA'},
    {'name': 'Lucy Liu', 'username': 'lucyliu', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Courteney Cox', 'username': 'courteneycoxofficial', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Michelle Rodriguez', 'username': 'mrodofficial', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Anne Hathaway', 'username': 'annehathaway', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Maria Menounos', 'username': 'mariamenounos', 'description': 'TV host', 'country': 'USA'},
    {'name': 'Liam Hemsworth', 'username': 'liamhemsworth', 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Drew Barrymore', 'username': 'drewbarrymore', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Catherine Zeta-Jones', 'username': 'catherinezetajones', 'description': 'Actress', 'country': 'UK'},
    {'name': 'Kate Hudson', 'username': 'katehudson', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Eva Longoria', 'username': 'evalongoria', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Katrina Kaif', 'username': 'katrinakaif', 'description': 'Actress', 'country': 'India'},
    {'name': 'Ralph Macchio', 'username': 'ralph_macchio', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Laverne Cox', 'username': 'lavernecox', 'description': 'Actress', 'country': 'USA'},
    {'name': 'Jaden Smith', 'username': 'c.syresmith', 'description': 'Actor and rapper', 'country': 'USA'},
    {'name': 'Jaden Springer', 'username': 'jaden', 'description': 'Basketball player', 'country': 'USA'},
    {'name': 'William Zabka', 'username': 'william_zabka', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Xolo Maridueña', 'username': 'xolo_mariduena', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Tanner Buchanan', 'username': 'tannerbuchananofficial', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Mary Mouser', 'username': 'missmarymmouser', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Peyton List', 'username': 'peytonlist', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Chase Stokes', 'username': 'hichasestokes', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Madelyn Cline', 'username': 'madelyncline', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Madison Bailey', 'username': 'madisonbaileybabe', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Samuel L. Jackson', 'username': 'samuelljackson', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Robert Downey Jr.', 'username': 'robertdowneyjr', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Paul Bettany', 'username': 'paulbettany', 'description': 'Actor', 'country': 'UK'},
    {'name': 'Don Cheadle', 'username': 'doncheadle', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Jon Favreau', 'username': 'jonfavreau', 'description': 'Director', 'country': 'USA'},
    {'name': 'Tom Hiddleston', 'username': 'twhiddleston', 'description': 'Actor', 'country': 'UK'},
    {'name': 'Mark Ruffalo', 'username': 'markruffalo', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Karen Gillan', 'username': 'karengillan', 'description': 'Actor', 'country': 'UK'},
    {'name': 'Sean Gunn', 'username': 'thejudgegunn', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Ryan Reynolds', 'username': 'vancityreynolds', 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Gwyneth Paltrow', 'username': 'gwynethpaltrow', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Cobie Smulders', 'username': 'cobiesmulders', 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Sebastian Stan', 'username': 'imsebastianstan', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Benedict Wong', 'username': 'wongrel', 'description': 'Actor', 'country': 'UK'},
    {'name': 'Hayley Atwell', 'username': 'wellhayley', 'description': 'Actor', 'country': 'UK'},
    {'name': 'Tom Cruise', 'username': 'tomcruise', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Jeremy Renner', 'username': 'jeremyrenner', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Adam Sandler', 'username': 'adamsandler', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Anthony Mackie', 'username': 'anthonymackie', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Jacob Batalon', 'username': 'lifeisaloha', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Jacob Elordi', 'username': 'jacobelordi', 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Marisa Tomei', 'username': 'marisatomei', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Jaimie Alexander', 'username': 'jaimiealexander', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Josh Brolin', 'username': 'joshbrolin', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Kat Dennings', 'username': 'katdenningsss', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Ian Somerhalder', 'username': 'iansomerhalder', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Paul Wesley', 'username': 'paulwesley', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Joseph Morgan', 'username': 'therealjosephmorgan', 'description': 'Actor', 'country': 'UK'},
    {'name': 'Daniel Gillies', 'username': 'mr.danielgillies', 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Claire Holt', 'username': 'claireholt', 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Phoebe Tonkin', 'username': 'phoebejtonkin', 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Riley Voelkel', 'username': 'lifeofrileyv', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Danielle Campbell', 'username': 'thedaniellecampbell', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Danielle Rose', 'username': 'danielleroserussell', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Evangeline Lilly', 'username': 'evangelinelillyofficial', 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Angourie Rice', 'username': 'angourierice', 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Emily VanCamp', 'username': 'emilyvancamp', 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Michael B. Jordan', 'username': 'michaelbjordan', 'description': 'Actor', 'country': 'USA'},
    {'name': 'Florence Pugh', 'username': 'florencepugh', 'description': 'Actor', 'country': 'UK'},
    {'name': 'Harry Styles', 'username': 'harrystyles', 'description': 'Singer', 'country': 'UK'},
    {'name': 'Liam Payne', 'username': 'liampayne', 'description': 'Singer', 'country': 'UK'},
    {'name': 'Zinedine Zidane', 'username': 'zidane', 'description': 'Footballer', 'country': 'France'},   
    {'name': 'Thierry Henry', 'username': 'thierryhenry', 'description': 'Footballer', 'country': 'France'},
    {'name': 'Luka Modrić', 'username': 'lukamodric10', 'description': 'Footballer', 'country': 'Croatia'},
    {'name': 'Kylian Mbappé', 'username': 'k.mbappe', 'description': 'Footballer', 'country': 'France'},
    {'name': 'Xavi Hernández', 'username': 'xavi', 'description': 'Footballer', 'country': 'Spain'},
    {'name': 'Kevin De Bruyne', 'username': 'kevindebruyne', 'description': 'Footballer', 'country': 'Belgium'},
    {'name': 'Toni Kroos', 'username': 'toni.kr8s', 'description': 'Footballer', 'country': 'Germany'},
    {'name': 'Sergio Ramos', 'username': 'sergioramos', 'description': 'Footballer', 'country': 'Spain'},
    {'name': 'Karim Benzema', 'username': 'karimbenzema', 'description': 'Footballer', 'country': 'France'},
    {'name': 'Sergio Busquets', 'username': '5sergiob', 'description': 'Footballer', 'country': 'Spain'},
    {'name': 'Robert Lewandowski', 'username': '_rl9', 'description': 'Footballer', 'country': 'Poland'},
    {'name': 'Lamine Yamal', 'username': 'lamineyamal', 'description': 'Footballer', 'country': 'Spain'},
    {'name': 'Luis Suárez', 'username': 'luissuarez9', 'description': 'Footballer', 'country': 'Uruguay'},
    {'name': 'Tom Brady', 'username': 'tombrady', 'description': 'Footballer', 'country': 'USA'},
    {'name': 'Josh Allen', 'username': 'joshallenqb', 'description': 'Footballer', 'country': 'USA'},
    {'name': 'Tyreek Hill', 'username': 'cheetah', 'description': 'Footballer', 'country': 'USA'},
    {'name': 'Peyton Manning', 'username': 'peytonmanning', 'description': 'Footballer', 'country': 'USA'},
    {'name': 'Travis Kelce', 'username': 'killatrav', 'description': 'Footballer', 'country': 'USA'},
    {'name': 'Harrison Butker', 'username': 'buttkicker7', 'description': 'Footballer', 'country': 'USA'},
    {'name': 'Rashee Rice', 'username': 'doub11e_r', 'description': 'Footballer', 'country': 'USA'},
    {'name': 'Isiah Pacheco', 'username': 'lil_poppy856', 'description': 'Footballer', 'country': 'USA'},
    {'name': 'Brock Purdy', 'username': 'brock.purdy13', 'description': 'Footballer', 'country': 'USA'},
    {'name': 'George Kittle', 'username': 'gkittle', 'description': 'Footballer', 'country': 'USA'},
    {'name': 'Christian McCaffrey', 'username': 'christianmccaffrey', 'description': 'Footballer', 'country': 'USA'},
    {'name': 'Gunna', 'username': 'gunna', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Future', 'username': 'future', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Metro Boomin', 'username': 'metroboomin', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Don Toliver', 'username': 'dontoliver', 'description': 'Singer', 'country': 'USA'},
    {'name': 'The Weeknd', 'username': 'theweeknd', 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Playboi Carti', 'username': 'playboicarti', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Khalid', 'username': 'thegr8khalid', 'description': 'Singer', 'country': 'USA'},
    {'name': 'Amitabh Bachchan', 'username': 'amitabhbachchan', 'description': 'Actor', 'country': 'India'},
    {'name': 'Sachin Tendulkar', 'username': 'sachintendulkar', 'description': 'Former Cricketer', 'country': 'India'},
    {'name': 'Alia Bhatt', 'username': 'aliaabhatt', 'description': 'Actress', 'country': 'India'},
    {'name': 'Ranveer Singh', 'username': 'ranveersingh', 'description': 'Actor', 'country': 'India'},
    {'name': 'Kareena Kapoor Khan', 'username': 'kareenakapoorkhan', 'description': 'Actress', 'country': 'India'},
    {'name': 'Badshah', 'username': 'badboyshah', 'description': 'Rapper, Singer', 'country': 'India'},
    {'name': 'MS Dhoni', 'username': 'mahi7781', 'description': 'Former Cricketer, Captain', 'country': 'India'},
    {'name': 'Rohit Sharma', 'username': 'rohitsharma45', 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Sonam Bajwa', 'username': 'sonambajwa', 'description': 'Punjabi Actress, Model', 'country': 'India'},
    {'name': 'Disha Patani', 'username': 'dishapatani', 'description': 'Actress', 'country': 'India'},
    {'name': 'Shubh', 'username': 'shubhworldwide', 'description': 'Punjabi Singer, Rapper', 'country': 'India'},
    {'name': 'AP Dhillon', 'username': 'apdhillon', 'description': 'Punjabi Singer, Rapper', 'country': 'India'},
    {'name': 'Sukha', 'username': '5ukha', 'description': 'Punjabi Singer, Lyricist', 'country': 'India'},
    {'name': 'Kid LAROI', 'username': 'thekidlaroi', 'description': 'Singer, Rapper', 'country': 'Australia'},
    {'name': 'Tate McRae', 'username': 'tatemcrae', 'description': 'Singer, Dancer', 'country': 'Canada'},
    {'name': 'Sunil Chhetri', 'username': 'chetri_sunil11', 'description': 'Former Footballer Player', 'country': 'India'},
    {'name': 'Simon Minter', 'username': 'miniminter', 'description': 'YouTuber, Gamer', 'country': 'UK'},
    {'name': 'Vikram Barn (Vik)', 'username': 'vikkstagram', 'description': 'YouTuber, Gamer', 'country': 'UK'},
    {'name': 'Olajide Olatunji (JJ)', 'username': 'ksi', 'description': 'YouTuber, Rapper', 'country': 'UK'},
    {'name': 'Tobi Brown', 'username': 'tobjizzle', 'description': 'YouTuber, Gamer', 'country': 'UK'},
    {'name': 'Ethan Payne', 'username': 'behzingagram', 'description': 'YouTuber, Gamer', 'country': 'UK'},
    {'name': 'Harry Lewis', 'username': 'wroetoshaw', 'description': 'YouTuber, Gamer', 'country': 'UK'},
    {'name': 'Josh Bradley', 'username': 'zerkaa', 'description': 'YouTuber, Gamer', 'country': 'UK'}
    ]


